-- Run this in SQL Plus or SQL Developer

-- FCM_COLLECTION sequence (for both ID and SERIAL)
CREATE SEQUENCE erp.fcm_collection_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_COL_HISTORY sequence
CREATE SEQUENCE erp.fcm_col_history_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_COL_DETAILS sequence
CREATE SEQUENCE erp.fcm_col_details_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_COL_PAYMENTS sequence
CREATE SEQUENCE erp.fcm_col_payments_serial_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_COL_SUMMARY sequence
CREATE SEQUENCE erp.fcm_col_summary_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_VIRTUAL_COMMISSION sequence
CREATE SEQUENCE erp.fcm_virtual_commission_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FCM_VIRTUAL_COMM_DETAILS sequence
CREATE SEQUENCE erp.fcm_virtual_comm_details_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FGL_TRANSACTIONS sequence
CREATE SEQUENCE erp.fgl_transactions_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FGL_INVOICES sequence
CREATE SEQUENCE erp.fgl_invoices_serial_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FGL_INVOICE_DETAILS sequence
CREATE SEQUENCE erp.fgl_invoice_details_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- FGL_NETTINGS sequence
CREATE SEQUENCE erp.fgl_nettings_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- ACCEPT_POLICIES sequence
CREATE SEQUENCE accept_policies_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- STG_POLICIES sequence
CREATE SEQUENCE stg_policies_id_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;