# Generated by Django 5.2.6 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.CharField(blank=True, max_length=255)),
                ('policy_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_flag', models.IntegerField(default=1)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'STG_POLICIES',
                'managed': False,
            },
        ),
    ]
