# Generated by Django 5.2.6 on 2026-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_stgpolicy'),
    ]

    operations = [
    ]
